// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {snapshot} from '../models';
import {config} from '../models';
import {main} from '../models';

export function AcceptAll():Promise<void>;

export function AcceptFile(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateTerminal():Promise<string>;

export function GetChangedFiles():Promise<Array<snapshot.FileChange>>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetFileDiff(arg1:string):Promise<Record<string, string>>;

export function GetStartupWorkspace():Promise<string>;

export function GetWorkspaceHistory():Promise<Array<config.WorkspaceEntry>>;

export function GetWorkspaceInfo():Promise<main.WorkspaceInfo>;

export function OpenInNewWindow(arg1:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<main.WorkspaceInfo>;

export function RemoveWorkspaceFromHistory(arg1:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RevertAll():Promise<void>;

export function RevertFile(arg1:string):Promise<void>;

export function SelectWorkspace():Promise<main.WorkspaceInfo>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
