// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {snapshot} from '../models';
import {config} from '../models';

export function AcceptAll():Promise<void>;

export function AcceptFile(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateSSHTerminal(arg1:main.SSHConfig):Promise<string>;

export function CreateTerminal():Promise<string>;

export function GetChangedFiles():Promise<Array<snapshot.FileChange>>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetFileDiff(arg1:string):Promise<Record<string, string>>;

export function GetRemoteWorkspaces():Promise<Array<config.RemoteWorkspaceEntry>>;

export function GetSSHConfigs():Promise<Array<config.SSHConfig>>;

export function GetStartupCommands():Promise<Array<config.StartupCommand>>;

export function GetStartupWorkspace():Promise<string>;

export function GetWorkspaceHistory():Promise<Array<config.WorkspaceEntry>>;

export function GetWorkspaceInfo():Promise<main.WorkspaceInfo>;

export function ListRemoteDir(arg1:string):Promise<Array<main.RemoteDirEntry>>;

export function OpenInNewWindow(arg1:string):Promise<void>;

export function OpenRemoteWorkspace(arg1:main.SSHConfig,arg2:string):Promise<main.WorkspaceInfo>;

export function OpenWorkspace(arg1:string):Promise<main.WorkspaceInfo>;

export function RefreshLocalWorkspace():Promise<main.WorkspaceInfo>;

export function RefreshRemoteWorkspace():Promise<main.WorkspaceInfo>;

export function RemoveRemoteWorkspace(arg1:string):Promise<void>;

export function RemoveSSHConfig(arg1:string):Promise<void>;

export function RemoveWorkspaceFromHistory(arg1:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RevertAll():Promise<void>;

export function RevertFile(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveRemoteWorkspace(arg1:config.RemoteWorkspaceEntry):Promise<void>;

export function SaveSSHConfig(arg1:config.SSHConfig):Promise<void>;

export function SaveStartupCommands(arg1:Array<config.StartupCommand>):Promise<void>;

export function SelectWorkspace():Promise<main.WorkspaceInfo>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
