// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptAll() {
  return window['go']['main']['App']['AcceptAll']();
}

export function AcceptFile(arg1) {
  return window['go']['main']['App']['AcceptFile'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateTerminal() {
  return window['go']['main']['App']['CreateTerminal']();
}

export function GetChangedFiles() {
  return window['go']['main']['App']['GetChangedFiles']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFileDiff(arg1) {
  return window['go']['main']['App']['GetFileDiff'](arg1);
}

export function GetWorkspaceHistory() {
  return window['go']['main']['App']['GetWorkspaceHistory']();
}

export function GetWorkspaceInfo() {
  return window['go']['main']['App']['GetWorkspaceInfo']();
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function RemoveWorkspaceFromHistory(arg1) {
  return window['go']['main']['App']['RemoveWorkspaceFromHistory'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RevertAll() {
  return window['go']['main']['App']['RevertAll']();
}

export function RevertFile(arg1) {
  return window['go']['main']['App']['RevertFile'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}
